services:

  n8n:
    image: docker.n8n.io/n8nio/n8n
    environments:
      - GENERIC_TIMEZONE="Europe/Rome"
      - TZ="Europe/Rome"
    ports:
      - 5678:5678
    volumes:
      - ./data:/home/node/.n8n
